feature/HH81 Get all students with pagination
Przekol/megak-v2-head-hunter-gr9-backend pull request #15
Opened 2023-05-08 20:04 UTC by EckhartPL

Get all students with pagination.

2023-05-08 22:20 UTC, EckhartPL commented
![](https://github.trello.services/images/mini-trello-icon.png) [[BE] Zwrócenie tablicy ze wszystkimi studentami](https://trello.com/c/MthRDZ8O/81-be-zwr%C3%B3cenie-tablicy-ze-wszystkimi-studentami)

2023-05-09 06:53 UTC, Przekol requested changes

2023-05-09 06:53 UTC, Przekol commented on src/students/students.controller.ts
> +  @Get('/all-students')
jesteśmy już w kontrolerze `students` nie musimy nazywać ścieżki `all-students`, wystarczy `all`, albo w ogóle `/` - konwencja tworzenia REST API mówi:
- tworzenie `/students` POST
- pobieranie wszystkich `/students` GET
- pobieranie pojedynczego `/students/:id` GET
-  i tak dalej :)

a że już mamy kontroller `students` to zostaje tylko dodać same `/`

2023-05-09 06:53 UTC, Przekol commented on src/students/students.controller.ts
> +  getAllStudents(@Query() pageOptionsDto: PageOptionsDto): Promise<PageDto<StudentsResponse>> {
`PageDto` nie jest typem tylko klasą - potrzebujemy tutaj typu, żeby front mógł do niego się podłaczyć. Klasy na front nie wyciągniesz

2023-05-09 06:53 UTC, Przekol commented on src/students/students.service.ts
> +    Logger.log(entities);
tutaj logger do usunięcia raczej

2023-05-09 06:53 UTC, Przekol commented on src/students/students.service.ts
> +  private getAllStudentsQuery(pageOptionsDto: PageOptionsDto): SelectQueryBuilder<Student> {
czy uda CI się pobrać tylko tych studentów którzy mają utworzony profil? Bo u mnie w bazie testowałem i wywala 500, bo nie u wszystkich mam utworzony profil. A faktycznie tak będize. Że póki Student się nie zaloguje i nie uzupełni danych to nie będzie wyświetlać się jego profil rekruterom

2023-05-09 06:53 UTC, Przekol commented on src/students/students.service.ts
> +    entities.forEach(entity => {
Nie można tej transformacji (mapowania - wyszło, że mówi się i tak i tak), przenieść do `mappers.response.ts` i częściowo skorzystać już z gotowych metod tam przygotowanych?
masz na pewno metodę do mapowania `grades` oraz `employmentExpectations`.
Można też przerobić moją metodę, by była jeszcze bardziej reużywalna, by potem poskładać wszystko jak klocki lego:)

2023-05-09 06:53 UTC, Przekol commented on src/students/students.service.ts
> +    const students: StudentsResponse[] = [];
po za tym, zamiast robić `forEach` to zrób sobie `map` na `students` i nie będziesz musiał robić `push`

```js
const students: StudentsResponse[] = entities.map(entity => ({
  studentId: entity.id,
  createdAt: entity.createdAt,
  details: {
    // ...
  },
  ```
  i tutaj świetnie uda się wrzucić metodę mapującą z odpowiedniego pliku

2023-05-09 07:12 UTC, Przekol commented on src/students/dto/page-meta.dto.ts
> +  @ApiProperty()
Czy tutaj potrzebujemy swaggera? czy ja czegoś nie rozumiem?:)

inna sprawa, to wszystko jest okej :) ale zawsze można spróbować zrobić to ładniej :)
Spróbuj zrobić tak (testowo i sprawdź czy Ci zadziała tak jak teraz)
```js
import { Transform } from 'class-transformer';

export class PageMetaDto {
  readonly page: number;

  readonly take: number;

  readonly itemCount: number;

  @Transform(({ obj }) => Math.ceil(obj.itemCount / obj.take))
  readonly pageCount: number;

  @Transform(({ obj }) => obj.page > 1)
  readonly hasPreviousPage: boolean;

  @Transform(({ obj }) => obj.page < obj.pageCount)
  readonly hasNextPage: boolean;
}
```
a potem w metodzie do pobierania:
```js
public async getAllStudents(pageOptionsDto: PageOptionsDto){
...
const pageMetaDto = plainToInstance(PageMetaDto, { ...pageOptionsDto, itemCount });

  return new PageDto(students, pageMetaDto);
  }
  ```

2023-05-09 18:34 UTC, Przekol commented on src/types/student/student.response.ts
> +export type StudentsResponse = {
tu też jest coś źle.. bo to typ dla pojedynczego studenta - trzeba to jakoś inaczej nazwać :)

2023-05-12 07:06 UTC, Przekol approved these changes

2023-05-12 07:06 UTC, Przekol commented on src/students/students.service.ts
> +      ) as unknown as SelectQueryBuilder<StudentProfileAndGrades>;
Tutaj chyba `unknown` nie trzeba. Usunąłem to i działało.

2023-05-12 07:07 UTC, Przekol commented on src/students/students.service.ts
> +  // eslint-disable-next-line max-lines-per-function
Pokazałbym Ci coś "ekstra" jak się tego pozbyć i zrobić ten kod jeszcze bardziej reużywalny, ale już chyba nie ma czasu póki co na coś takiego :)

2023-05-12 16:41 UTC, Przekol requested changes

2023-05-12 16:41 UTC, Przekol commented on src/types/student/student.response.ts
>    createdAt: Date;
Brakuje firstName i lastName!

2023-05-12 16:47 UTC, Przekol commented on src/types/student-profile/student-profile.ts
> +  profile: EmploymentExpectations;
czemu tu 'profile' jest podpięty pod EmploymentExpectations? pomieszałeś

2023-05-12 16:49 UTC, Przekol commented on src/types/student/page-meta-dto-parameters.ts
> +import { PageOptionsDto } from 'src/students/dto';
musisz tu usunąć i zrobić typ, i sobie potem ten typ tutaj zaimportować. W `types` nie importujemy niczego z reszty aplikacji. Inaczej wywali błędy (to właśnie poprawiałem w ostatnim fixie)

2023-05-16 13:02 UTC, merged