Feature/hh80
Przekol/megak-v2-head-hunter-gr9-backend pull request #16
Opened 2023-05-08 23:23 UTC by EckhartPL

Get One Student.

2023-05-08 23:24 UTC, EckhartPL commented
![](https://github.trello.services/images/mini-trello-icon.png) [[BE] Zwrócenie pojedynczego Studenta](https://trello.com/c/9KhHg0wi/80-be-zwr%C3%B3cenie-pojedynczego-studenta)

2023-05-09 08:15 UTC, Przekol commented on src/utils/swagger/schemas/students.schema.ts
> +export const getOneStudentResponseSchema = {
to samo co przy example

2023-05-09 08:15 UTC, Przekol commented on src/utils/swagger/examples/students.example.ts
> +export const getOneStudentResponseExample = {
a to nie będzie to samo co studentProfileResponseExample ? dopasowałbym się do tamtego :) bez sensu tworzyć kolejny przykład z takimi samymi danymi :)

2023-05-09 08:15 UTC, Przekol commented on src/students/students.service.ts
> +  private getOneStudentQuery(studentId: string): Promise<Student> {
już zrobiłem pobieranie pojedynczego Studenta 
```js
 getStudentById(id: string): Promise<Student> {
    return Student.findOne({ where: { user: { id } }, relations: { user: true, grades: true } });
  }
  ```
  I działa :)

i pewnie wystarczyło się podpiąć do tego, stworzyć endpoint, swaggera i iść spać :)

  ale fakt, może warto korzystać z `dataSource` - podobno lepsze rozwiazanie przy tak sporych połączeniach.
  W takim wypadku powinieneś też od razu przypiąć tą metodę do mojego kodu, odpowiednio poprawić, refakturyzować i usunąć tamtą metodę. Bo teraz mamy 2 metody robiące to samo

2023-05-09 08:15 UTC, Przekol commented on src/students/students.service.ts
> +  private getOneStudentQuery(studentId: string): Promise<Student> {
i oczywiście wszystko przetestować

2023-05-12 07:18 UTC, Przekol requested changes

2023-05-12 07:18 UTC, Przekol commented on src/students/students.service.ts
> +          return {
Czemu tego nie przeniosłeś do `mappers.response.ts`?
a w ogóle czy to jest potrzebne? bo widzę, że masz już podłączoną metodę mapującą, więc robisz chyba 2 razy to samo

2023-05-12 07:18 UTC, Przekol commented on src/students/students.service.ts
> +    Logger.log({ queryBuilder });
loger do usunięcia

2023-05-12 07:18 UTC, Przekol commented on src/students/students.service.ts
> +    const queryBuilder = await this.getOneStudentQuery(studentId);
Musisz jeszcze złapać błąd, że przy złym ID powinno wyrzucać 404. Obecnie wywala 500.

2023-05-12 07:18 UTC, Przekol commented on src/students/students.service.ts
> +    return student;
tutaj możesz dać od razu `return mapGetOneStudentProfileResponse(queryBuilder)`

2023-05-16 13:02 UTC, merged